[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "meu-app"
version = "0.1.0"  # versão fixa para evitar procurar __version__
requires-python = ">=3.11"
